# Generated by Django 5.1.6 on 2025-02-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0003_add_timetable_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawleddata',
            name='data_type',
            field=models.CharField(choices=[('medians', 'Medians'), ('orc_department_courses', 'ORC Department Courses'), ('course_timetable', 'Course Timetable')], max_length=32),
        ),
    ]
