# Generated by Django 5.1.6 on 2025-02-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_student_unauth_session_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='crosslisted_courses',
            field=models.ManyToManyField(blank=True, to='web.course'),
        ),
    ]
